import type { Component } from 'vue';
import {
    ArrowsExchangeIcon,
    BabyCarriageIcon,
    BarbellIcon,
    BoltIcon,
    BookIcon,
    BriefcaseIcon,
    BuildingBankIcon,
    BuildingStoreIcon,
    BusIcon,
    CarIcon,
    CashIcon,
    ChartBarIcon,
    CoffeeIcon,
    CreditCardIcon,
    DeviceGamepad2Icon,
    DeviceMobileIcon,
    DropletIcon,
    FlameIcon,
    GiftIcon,
    HeartIcon,
    HomeIcon,
    LeafIcon,
    MapPinIcon,
    MovieIcon,
    MusicIcon,
    PawIcon,
    PigMoneyIcon,
    PlaneIcon,
    Receipt2Icon,
    SchoolIcon,
    ShirtIcon,
    ShoppingCartIcon,
    StarIcon,
    TagIcon,
    ToolsIcon,
    ToolsKitchen2Icon,
    UsersIcon,
    UserIcon,
    WalletIcon,
    WifiIcon,
    WorldIcon
} from 'vue-tabler-icons';

export type CategoryIconKey = (typeof CATEGORY_ICON_KEYS)[number];

export const CATEGORY_ICON_KEYS = [
    'home',
    'building-store',
    'shopping-cart',
    'car',
    'bus',
    'plane',
    'utensils',
    'coffee',
    'heart',
    'gift',
    'device-mobile',
    'wifi',
    'book',
    'briefcase',
    'cash',
    'credit-card',
    'wallet',
    'pig-money',
    'chart-bar',
    'arrows-exchange',
    'building-bank',
    'users',
    'user',
    'baby-carriage',
    'shirt',
    'device-gamepad',
    'music',
    'movie',
    'barbell',
    'leaf',
    'droplet',
    'bolt',
    'flame',
    'tools',
    'school',
    'world',
    'map-pin',
    'paw',
    'star',
    'receipt',
    'tag'
] as const;

const CATEGORY_ICON_MAP: Record<CategoryIconKey, Component> = {
    home: HomeIcon,
    'building-store': BuildingStoreIcon,
    'shopping-cart': ShoppingCartIcon,
    car: CarIcon,
    bus: BusIcon,
    plane: PlaneIcon,
    utensils: ToolsKitchen2Icon,
    coffee: CoffeeIcon,
    heart: HeartIcon,
    gift: GiftIcon,
    'device-mobile': DeviceMobileIcon,
    wifi: WifiIcon,
    book: BookIcon,
    briefcase: BriefcaseIcon,
    cash: CashIcon,
    'credit-card': CreditCardIcon,
    wallet: WalletIcon,
    'pig-money': PigMoneyIcon,
    'chart-bar': ChartBarIcon,
    'arrows-exchange': ArrowsExchangeIcon,
    'building-bank': BuildingBankIcon,
    users: UsersIcon,
    user: UserIcon,
    'baby-carriage': BabyCarriageIcon,
    shirt: ShirtIcon,
    'device-gamepad': DeviceGamepad2Icon,
    music: MusicIcon,
    movie: MovieIcon,
    barbell: BarbellIcon,
    leaf: LeafIcon,
    droplet: DropletIcon,
    bolt: BoltIcon,
    flame: FlameIcon,
    tools: ToolsIcon,
    school: SchoolIcon,
    world: WorldIcon,
    'map-pin': MapPinIcon,
    paw: PawIcon,
    star: StarIcon,
    receipt: Receipt2Icon,
    tag: TagIcon
};

export function isCategoryIconKey(value: string | null | undefined): value is CategoryIconKey {
    return !!value && (CATEGORY_ICON_KEYS as readonly string[]).includes(value);
}

export function resolveCategoryIcon(key: string | null | undefined): Component {
    if (isCategoryIconKey(key)) return CATEGORY_ICON_MAP[key];
    return TagIcon;
}
